#!/bin/bash

# If not running interactively, don't do anything
case $- in
  *i*) ;;
  *) return ;;
esac

case `uname` in
  Darwin*)
    export CLICOLOR=1 ;;
esac

if [ -x /usr/bin/dircolors ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

# No duplicates!
export HISTSIZE=4096
export HISTCONTROL=erasedups
export HISTIGNORE=ls:cd
export VISUAL=vim
export EDITOR=$VISUAL

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

function reloadssh() {
  eval "$(tmux show-env -s |grep '^SSH_')"
}

if [ -x /usr/bin/tput ] && tput setaf 1 >& /dev/null; then
  export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
else
  export PS1='\u@\h:\W\$ '
fi

[ -f /opt/conda/etc/profile.d/conda.sh ] && . /opt/conda/etc/profile.d/conda.sh
[ -f ~/.fzf.bash ] && . ~/.fzf.bash

# On some machines (Ubuntu 18.04), non-login interactive shells do not load
# bash completions. Load them if not.
if [ -z "${BASH_COMPLETION_VERSINFO-}" ]; then
  if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
      . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
      . /etc/bash_completion
    fi
  fi
fi
